### ISSUE TITLE
Segmentation faults

### ISSUE THREAD

**Issue by DominikGlodzik** [cancerit/dockstore-cgpmap#14]
Dear Colleagues,

I am recurrently getting errors when mapping ~80x WGS samples, using the singularity image. I wonder if you could advise any checks I could do on the process or parameters.

I am running the image similarly to:

`export CGPMAP_VER=3.0.0
singularity pull docker://quay.io/wtsicgp/dockstore-cgpmap:$CGPMAP_VER
singularity exec\
 --workdir /.../workspace  \
 --home /.../workspace:/home  \
 --bind /.../ref/human:/var/spool/ref:ro  \
 --bind /.../example_data/cgpmap/insilico_21:/var/spool/data:ro  \
 dockstore-cgpmap-${CGPMAP_VER}.simg  \
 ds-cgpmap.pl  \
 -r /var/spool/ref/core_ref_GRCh37d5.tar.gz  \
 -i /var/spool/ref/bwa_idx_GRCh37d5.tar.gz  \
 -s SOMENAME  \
 -t 12 \
 /var/spool/data/\*.fastq
`

The errors I get are similar to this one:
`more PCAP_Bwa_bwa_mem.2.err
\+ set -o pipefail
\+ /opt/wtsi-cgp/bin/bwa mem -v 1 -p -R \"@RG\tID:2\tSM:M00026\" -t 6 /home/refer
ence_files/genome.fa /home/tmpMap_M00026/split/2/i.fastq.gz
\+ /opt/wtsi-cgp/bin/reheadSQ -d /home/reference_files/genome.fa.dict
\+ /opt/wtsi-cgp/biobambam2/bin/bamsort fixmate=1 inputformat=sam level=1 tmpfile
=/home/tmpMap_M00026/bamsort.2_tmp O=/home/tmpMap_M00026/sorted/2_i.fastq.gz
_sorted.bam outputthreads=5 calmdnm=1 calmdnmrecompindetonly=1 calmdnmreference=
/home/reference_files/genome.fa
[V] Reading alignments from source.
[V] 1M
[V] 2M
[V] 3M
[V] 4M
[V] 5M
[V] 6M
[V] 7M
/home/tmpMap_M00026/logs/PCAP_Bwa_bwa_mem.2.sh: line 3: 19166 Broken pipe    
        /opt/wtsi-cgp/bin/bwa mem -v 1 -p -R \"@RG\tID:2\tSM:M00026\" -t 6 /home
/reference_files/genome.fa /home/tmpMap_M00026/split/2/i.fastq.gz
     19167                       | /opt/wtsi-cgp/bin/reheadSQ -d /home/reference
_files/genome.fa.dict
     19168 Segmentation fault      (core dumped) | /opt/wtsi-cgp/biobambam2/bin/
bamsort fixmate=1 inputformat=sam level=1 tmpfile=/home/tmpMap_M00026/bamsort.
2_tmp O=/home/tmpMap_M00026/sorted/2_i.fastq.gz_sorted.bam outputthreads=5 cal
mdnm=1 calmdnmrecompindetonly=1 calmdnmreference=/home/reference_files/genome.fa
Command exited with non-zero status 139
3594.45user 12.26system 9:55.32elapsed 605%CPU (0avgtext+0avgdata 6201544maxresi
dent)k
`

On smaller fastq files the jobs sometimes complete with and without errors. On larger fastq files they consistently give errors, but after variable about of time.
I also previously successfully aligned a WGS 40x case using this code.

Any advice on how to successfully execute the mapping process is really appreciated. Kind regards

**Comment by keiranmraine** [comment]
Hi Dominik,

We have been made aware of some issues running data under singularity.  We hope to start investigating this in depth over the next few months but reporting this is very helpful especially if you can also provide the _version of singularity_ you are running under.

Thanks

**Comment by DominikGlodzik** [comment]
Hi Keiran,

thank you for your response!

Have you encountered similar issue with docker? I can try it instead.

Dominik

**Comment by DominikGlodzik** [comment]
Thank you Keiran, running through Docker solved the mapping problem.
