### ISSUE TITLE
Mate pairs and RNEXT, PNEXT fields in the result bam file

### ISSUE THREAD

**Issue by DominikGlodzik** [cancerit/dockstore-cgpmap#17]
Hello Colleagues,

I realise that the source of my downstream problem is that the bam files aligned with cgpmap always have zeros in RNEXT and PNEXT. 
Eg A00125:128:HG5TCDSXX:1:1101:11388:1141    0    X    74361818    60    151M    *    **0    0**    ATAGAATATAATTAACAT...

I am guessing bwa does not see the read pairs from two fast files as pairs. I checked read names in two fast files, and they match. Eg matching lines from the two fast files are:
Fastq1 
@A00155:110:HGCVKDSXX:1:1101:16107:7435 1:N:0:ACGCACCT+GGTGAAGG
TTGGA...
Fast2
@A00155:110:HGCVKDSXX:1:1101:16107:7435 2:N:0:ACGCACCT+GGTGAAGG
ATCCA

Could there be something wrong with my fastq files? Alternatively, the way I am running Cgpmap (shown below)?

I appreciate your help. Dominik

`
export CGPMAP_VER=3.0.0
singularity exec \
--workdir /home/workspace  \
--home /home/dglodzik/:/home  \
--bind /home/dglodzik/referenceData:/var/spool/ref:ro  \
--bind /home/dglodzik/testData:/var/spool/data:ro  \
dockstore-cgpmap-${CGPMAP_VER}.simg \
 ds-cgpmap.pl \
 -r /var/spool/ref/core_ref_GRCh37d5.tar.gz \
 -i /var/spool/ref/bwa_idx_GRCh37d5.tar.gz \
 -s testSample \
 -t 6 \
 /var/spool/data/test_*.fastq.gz       
`

**Comment by keiranmraine** [comment]
Hi Dominik,

The code requires the files to have a specific naming convention so that it can pair the files:

https://github.com/cancerit/PCAP-core/blob/develop/bin/bwa_mem.pl#L398-L402

Unfortunately this isn't covered in the documentation here so that does need correcting.

Can you confirm that your files follow this convention?

**Comment by keiranmraine** [comment]
Added to [wiki](https://github.com/cancerit/dockstore-cgpmap/wiki#fastq-file-name-conventions)
