### ISSUE TITLE
Is unaligning BAMs necessary?

### ISSUE THREAD

**Issue by Mousiekin** [cancerit/dockstore-cgpmap#27]
With dockstore-cgpmap_3.3.0.sif is it necessary to unalign BAM files before mapping or is this adequately catered for by your pipeline. Empirically it does not seem to be required. Please can you clarify this, and whether this is true for both bwamem and bwamem2 with or without bwakit. Thanks, Marian

**Comment by keiranmraine** [comment]
When BAM provided as input the pipeline will convert back to paired fastq before mapping (during split step).

**Comment by Mousiekin** [comment]
That is absolutely fantastic, no wonder it acts the same! Brilliant thanks.

**Comment by keiranmraine** [comment]
In can't close not being in he team anymore, @AndyMenzies I've answered for you ;)

**Comment by AndyMenzies** [comment]
Thanks Keiran, closing ticket. :)
